export const POST_COMMENT = "POST_COMMENT";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_SINGLE_COMMENT_REQUEST = "FETCH_SINGLE_COMMENT_REQUEST";
export const FETCH_SINGLE_COMMENT_SUCCESS = "FETCH_SINGLE_COMMENT_SUCCESS";
export const MORE_COMMENTS = "MORE_COMMENTS";
export const EDIT_COMMENT_REQUEST = "EDIT_COMMENT_REQUEST";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const SENDING = "SENDING";
/**Action to reset the sending state. */
export const NOT_SENDING = "NOT_SENDING";
export const FAILED = "FAILED";
export const TOGGLE_COMMENT_LIKE = "TOGGLE_COMMENT_LIKE";