// export const FETCH_HASHTAGS = "FETCH_HASHTAGS";
export const FETCH_HASHTAGS_FINISHED = "FETCH_HASHTAGS_FINISHED";
export const FETCH_MORE_HASHTAGS = "FETCH_MORE_HASHTAGS";
export const FETCH_HASHTAGS_REQUEST = "FETCH_HASHTAGS_REQUEST";
export const FETCH_HASHTAGS_SUCCESS = "FETCH_HASHTAGS_SUCCESS";