export const FETCH_MESSAGES_REQUEST = "FETCH_MESSAGES_REQUEST";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_NEW_MESSAGES_SUCCESS = "FETCH_NEW_MESSAGES_SUCCESS";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEARCH_PERSON_SUCCESS = "SEARCH_PERSON_SUCCESS";
export const SEARCH_PERSON_REQUEST = "SEARCH_PERSON_REQUEST";
export const SEARCH_PERSON_RESET = "SEARCH_PERSON_RESET";
