export const FETCH_NOTIFICATIONS_REQUEST = "FETCH_NOTIFICATIONS_REQUEST";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NEW_NOTIFICATIONS_SUCCESS = "FETCH_NEW_NOTIFICATIONS_SUCCESS";
export const READ_ALL_NOTIFICATIONS = "READ_ALL_NOTIFICATIONS";
export const READ_ONE_NOTIFICATION = "READ_ONE_NOTIFICATION";