export const STORE_POST_REQUEST = "STORE_POST_REQUEST";
export const STORE_POST_SUCCESS = "STORE_POST_SUCCESS";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const FETCH_ALL_POSTS_REQUEST = "FETCH_ALL_POSTS_REQUEST";
export const FETCH_ALL_POSTS_SUCCESS = "FETCH_ALL_POSTS_SUCCESS";
export const FETCH_SINGLE_POST_REQUEST = "FETCH_SINGLE_POST_REQUEST";
export const FETCH_SINGLE_POST_SUCCESS = "FETCH_SINGLE_POST_SUCCESS";
export const FETCH_ALL_POSTS_FAILURE = "FETCH_ALL_POSTS_FAILURE";
export const PIN_POST_REQUEST = "PIN_POST_REQUEST";
export const PIN_POST_SUCCESS = "PIN_POST_SUCCESS";
export const PINNING_POST_RESET = "PINNING_POST_RESET";

/**No more posts to fetch. */
export const FETCH_ALL_POSTS_FINISHED = "FETCH_ALL_POSTS_FINISHED";
