export const FETCH_USER_POSTS_REQUEST = "FETCH_USER_POSTS_REQUEST";
export const FETCH_USER_POSTS_SUCCESS = "FETCH_USER_POSTS_SUCCESS";
export const UPDATE_USER_POSTS = "UPDATE_USER_POSTS";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";